# Generated by Django 5.0.6 on 2024-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0002_alter_ourteam_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('username', models.CharField(max_length=20, null=True, unique=True, verbose_name='Username')),
                ('telegram_id', models.PositiveIntegerField(max_length=20, unique=True, verbose_name='Telegram ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'products_users',
            },
        ),
    ]
