# Generated by Django 5.0.6 on 2024-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0003_productsusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsusers',
            name='telegram_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
