# Generated by Django 5.0.6 on 2024-06-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0004_alter_productsusers_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('poroduct_name', models.CharField(max_length=50, verbose_name='Maxsulot nomi ')),
                ('photo', models.CharField(max_length=200, verbose_name='Rasm file_id')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx')),
                ('description', models.TextField(max_length=300, verbose_name='Maxsulto xaqida')),
                ('category_code', models.CharField(max_length=30, verbose_name='Category code')),
                ('category_name', models.CharField(max_length=40, verbose_name='Kategoriya nomi')),
                ('subcategory_code', models.CharField(max_length=50, verbose_name='Ost_categoriya kodi')),
                ('subcategory_name', models.CharField(max_length=50, verbose_name='Ost-kategoriya nomi')),
            ],
        ),
    ]
