# Generated by Django 5.0.6 on 2024-06-18 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0005_productsproducts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsproducts',
            table='products_product',
        ),
    ]
