# Generated by Django 5.0.6 on 2024-06-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_models', '0006_alter_productsproducts_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsusers',
            name='telegram_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
    ]
